[package]
name = "unit_test"
version = "0.1.0"
authors = ["Alexander Mennborg <alexander.mennborg@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nom_locate = "1"
sqrrlc = { path = "../../" }
